### ISSUE TITLE
gcc7: why force universal_archs on powerpc?

### ISSUE THREAD

**Issue by devernay** [kencu/LeopardPorts#2]
Why is universa_archs set to ppc ppc64 on powerpc?
Leopard doesn't have ppc64 AFAIK:
```
$ /usr/bin/file /usr/lib/libgcc_s.10.5.dylib 
/usr/lib/libgcc_s.10.5.dylib: Mach-O universal binary with 3 architectures
/usr/lib/libgcc_s.10.5.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library stub x86_64
/usr/lib/libgcc_s.10.5.dylib (for architecture i386):	Mach-O dynamically linked shared library stub i386
/usr/lib/libgcc_s.10.5.dylib (for architecture ppc7400):	Mach-O dynamically linked shared library stub ppc
```

it also breaks building universal gcc.

universal gcc is very useful, especially with https://github.com/devernay/macportsGCCfixup which enables building for multiple archs on the command-line

**Comment by kencu** [comment]
I was working on getting 64 bit builds working with clang-3.8, to try to get some further headway on a few issues that I thought could be resolved with that (like the eh_frames, for exceptions). So I rebuilt libgcc_s with a 64 bit PPC slice as well, and was hoping to go down that road. Ultimately though, I didn't have success (so far! - I'm persistent!).
```
$ file /usr/lib/libgcc_s.10.5.dylib
/usr/lib/libgcc_s.10.5.dylib: Mach-O universal binary with 4 architectures
/usr/lib/libgcc_s.10.5.dylib (for architecture i386):	Mach-O dynamically linked shared library stub i386
/usr/lib/libgcc_s.10.5.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library stub x86_64
/usr/lib/libgcc_s.10.5.dylib (for architecture ppc7400):	Mach-O dynamically linked shared library stub ppc
/usr/lib/libgcc_s.10.5.dylib (for architecture ppc64):	Mach-O 64-bit dynamically linked shared library stub ppc64
```

**Comment by kencu** [comment]
Now that gcc6 and gcc7 support the -arch flag, it has crossed my mind that with some surgery on the Portfile (which always assumed that gcc couldn't handle the -arch flag, so disabled it), we might get a build with all arches (i386, x86_64, ppc, and ppc64) to build on PPC.
